### ISSUE TITLE
[WalletConnect] Unsupported namespace methods in the approved session

### ISSUE THREAD

**Issue by Sparragus** [safe-global/safe-react-apps#709]
## Description
When a dapp wants to connect to a wallet using WalletConnect V2, it needs to propose a session. In the proposed session, the dapp declares which RPC methods are required for it to work properly. It can also declare additional _optional_ methods.

If the wallet application supports the required methods, but only a subset of the optional methods, it should approve the session with only the method/namespace it supports.

In the WalletConnect Safe App, we're approving ALL the methods requested (required + optional) even when the Wallet Connect Safe App doesn't support them. This is happening here: https://github.com/safe-global/safe-react-apps/blob/development/apps/wallet-connect/src/hooks/useWalletConnectV2.tsx#L221

Instead of approving the session with all the requested methods, only supported methods should be approved. 

The list of currently supported methods can be found in the [safe-apps-provider](https://github.com/safe-global/safe-apps-sdk/blob/main/packages/safe-apps-provider/src/provider.ts#L32).

### Impact
This bug is currently affecting users that use `wagmi` to connect their dapp to the WalletConnect Safe App. Personally, it's impacting me in my work ([Immunefi)](https://immunefi.com/)), but also other users in the internet. See https://twitter.com/0xDrewF/status/1665724631360077825, for example.

The bug is blowing up for `wagmi` users because their connector asks if there is support for `wallet_addEthereumChain`, the the Safe App is saying yes. See https://github.com/wagmi-dev/references/blob/main/packages/connectors/src/walletConnect.ts#LL239C34-L239C34. It then proceeds to use a mehtod which isn't supported.

### Suggested changes
1. Revert commits d9bf862cf388042e4805e391159cf840b033e0b3 and d39bcb18b4eeeecc55b8a2e64953772d53eca3b8. These commits were introduced in #657. FWIW: When this change was introduced, there was acknowledgement that it was an out-of-scope change. See https://github.com/safe-global/safe-react-apps/pull/657/commits/d9bf862cf388042e4805e391159cf840b033e0b3#r1185284454.
2. Release a new version of the WalletConnect Safe App.
3. Fix the bug by checking the list of required and optional methods, and only approve the session if the required can be fulfilled, and only with the supported optional methods.

I'll be happy to assist with these changes. As a starting point, here's a PR: https://github.com/safe-global/safe-react-apps/pull/710

## Environment
 - Browser: All. Example dapp: https://kmdt6c.csb.app
 - Wallet: n/a
 - Safe: All. Example: https://app.safe.global/apps/open?safe=gor:0xA632d4A98eA44A5bf02229158d2c954B3782eB50&appUrl=https%3A%2F%2Fapps-portal.safe.global%2Fwallet-connect
 - Environment: All

## Steps to reproduce
 1. Go to https://kmdt6c.csb.app/ (source code here: https://codesandbox.io/s/black-butterfly-kmdt6c?file=/src/App.tsx)
 2. Click connect, and connect to a Safe. Here's one I use in goerli. https://app.safe.global/apps/open?safe=gor:0xA632d4A98eA44A5bf02229158d2c954B3782eB50&appUrl=https%3A%2F%2Fapps-portal.safe.global%2Fwallet-connect.
 3. You'll see an error on both apps: `"wallet_addEthereumChain" not implemented`.

## Expected result
No error. Successful WalletConnect v2 connection

## Obtained result
An error on both apps: `"wallet_addEthereumChain" not implemented`.

## Screenshots
![image](https://github.com/safe-global/safe-react-apps/assets/80982/bff0a88e-fc70-4bbc-b570-4ece537af2a1)
![image](https://github.com/safe-global/safe-react-apps/assets/80982/6f8bd3db-7758-4fbc-abb9-425f6b0b8264)

**Comment by Sparragus** [comment]
Fixed in https://github.com/safe-global/safe-react-apps/pull/706.

**Comment by zigzag-way** [comment]
I still get this bug.
For ex I can not connect to THENA.FI using SafePal. I get this error while trying to connect through WalletConnect.

**Comment by damianlluch** [comment]
I have this error too
